[package]
name = "chatter-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
serde = "1.0.195"
serde_derive = "1.0.195"
serde_json = "1.0.111"
chatter-types = {path="../chatter-types"}
